/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    chaty: Chaty;
    oblasti: Oblasti;
    strediska: Strediska;
    vylety: Vylety;
    razitka: Razitka;
    clanky: Clanky;
    fotky: Fotky;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    chaty: {
      fotky: 'fotky';
      razitka: 'razitka';
      clanky: 'clanky';
    };
  };
  collectionsSelect: {
    chaty: ChatySelect<false> | ChatySelect<true>;
    oblasti: OblastiSelect<false> | OblastiSelect<true>;
    strediska: StrediskaSelect<false> | StrediskaSelect<true>;
    vylety: VyletySelect<false> | VyletySelect<true>;
    razitka: RazitkaSelect<false> | RazitkaSelect<true>;
    clanky: ClankySelect<false> | ClankySelect<true>;
    fotky: FotkySelect<false> | FotkySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Centrální entita webu. Žádný profil nejde ven poloprázdný — rozpracované drží koncept (draft).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chaty".
 */
export interface Chaty {
  id: number;
  nazev: string;
  /**
   * Část adresy stránky. Nevyplněný se vytvoří z názvu.
   */
  slug: string;
  zeme?: ('cz' | 'sk' | 'pl' | 'at' | 'de' | 'ch' | 'it' | 'si' | 'fr') | null;
  /**
   * Taxonomie dle plánu kap. 5.
   */
  typ?: ('obsluhovana' | 'utulna' | 'bivak' | 'horsky-hotel' | 'rozhledna') | null;
  stav?: ('v-provozu' | 'mimo-provoz' | 'zanikla') | null;
  aliasy?:
    | {
        nazev: string;
        poznamka?: string | null;
        id?: string | null;
      }[]
    | null;
  lat?: number | null;
  lng?: number | null;
  vyska?: number | null;
  oblast?: (number | null) | Oblasti;
  obec?: string | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniLokace?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Nevyplněno = nezjištěno.
   */
  nocleh?: ('ano' | 'ne') | null;
  pokoje?:
    | {
        typ?: string | null;
        luzek?: number | null;
        id?: string | null;
      }[]
    | null;
  kapacita?: number | null;
  cenyOrientacne?: string | null;
  rezervaceUrl?: string | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniNocleh?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Nevyplněno = nezjištěno.
   */
  kuchyne?: ('ano' | 'ne') | null;
  typObcerstveni?: ('restaurace' | 'bufet' | 'kiosek') | null;
  specialita?: string | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniObcerstveni?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Nevyplněno = nezjištěno.
   */
  voda?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  wc?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  sprchy?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  platbaKartou?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  wifi?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  psi?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  nabijeni?: ('ano' | 'ne') | null;
  /**
   * Nevyplněno = nezjištěno.
   */
  lyzarna?: ('ano' | 'ne') | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniSluzby?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  sezona?: string | null;
  otviraciDoba?: string | null;
  zimniProvoz?: string | null;
  kontakty?: {
    telefon?: string | null;
    email?: string | null;
    web?: string | null;
    facebook?: string | null;
    instagram?: string | null;
  };
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniProvoz?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  trasy?:
    | {
        vychoziBod: string;
        casMin?: number | null;
        prevyseni?: number | null;
        znaceni?: ('cervena' | 'modra' | 'zelena' | 'zluta' | 'cerna' | 'jine') | null;
        obtiznost?: ('snadna' | 'stredni' | 'narocna') | null;
        poznamka?: string | null;
        delkaKm?: number | null;
        /**
         * Pole dvojic [km, výška v m]: [[0, 769], [1.2, 850], …]. Zdroj bodů patří do ověření skupiny Přístup — nedomýšlet.
         */
        vyskovyProfil?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  autem?: string | null;
  lanovka?: string | null;
  verejnaDoprava?: {
    zastavka?: string | null;
    idosUrl?: string | null;
  };
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniPristup?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  rokVzniku?: number | null;
  /**
   * Přestavby, požáry, přejmenování…
   */
  milniky?:
    | {
        rok?: number | null;
        udalost: string;
        id?: string | null;
      }[]
    | null;
  historieText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniHistorie?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Krátké představení pro karty a náhledy (1–2 věty).
   */
  perex?: string | null;
  /**
   * Článek jako v knižním průvodci: poloha a okolí, historie, dnešní provoz a zázemí, přístup, na závěr odstavec o tom, odkud údaje pocházejí a co ověřené není. Délka se řídí tím, co je doložené — u dobře podložených chat 400–600 slov, u chudě doložených 120–200. Nic nedomýšlet: co není v profilu doložené, do textu nepatří. Tvrzení z druhé ruky připsat zdroji („podle…"), rozpory přiznat. Bez cen, telefonů, e-mailů, URL, GPS a čísel turistických známek.
   */
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Krátké pozoruhodné údaje a „nej" (nejstarší, nejvýše položená, největší, unikátní specialita…) pro budoucí žebříčky rekordů i highlight na profilu. Sbírej je rovnou při zjišťování dat. Superlativ = tvrzení → uveď zdroj, nedomýšlet. Spočitatelná „nej" (dle rokVzniku/výšky/kapacity) sem psát nemusíš — vezmou se z polí.
   */
  zajimavosti?:
    | {
        text: string;
        /**
         * Pro řazení do žebříčků „nej" (volitelné).
         */
        kategorie?: ('stari' | 'vyska' | 'velikost' | 'gastro' | 'jine') | null;
        /**
         * Odkud údaj/tvrzení pochází (web, provozovatel, kniha). Superlativ bez zdroje nezapisovat.
         */
        zdroj?: string | null;
        id?: string | null;
      }[]
    | null;
  fotky?: {
    docs?: (number | Fotky)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  webkamera?: string | null;
  /**
   * Základ grafu pro plánovač přechodů — čas pěšího přechodu mezi chatami.
   */
  sousedniChaty?:
    | {
        chata: number | Chaty;
        casPrechodMin?: number | null;
        id?: string | null;
      }[]
    | null;
  razitka?: {
    docs?: (number | Razitka)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  clanky?: {
    docs?: (number | Clanky)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Souhrn hlavních zdrojů celého profilu.
   */
  zdroje?:
    | {
        popis: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Jen pro redakci, nikdy se nezobrazují na webu.
   */
  interniPoznamky?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hierarchie země → pohoří → podoblast. Přehledy chat a výletů se generují z dat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oblasti".
 */
export interface Oblasti {
  id: number;
  nazev: string;
  /**
   * Část adresy stránky. Nevyplněný se vytvoří z názvu.
   */
  slug: string;
  /**
   * Země je samostatné pole — hierarchii tvoří pohoří a podoblasti. „Turistická oblast" je pro celky, které pohoří nejsou (skalní města).
   */
  typ: 'pohori' | 'podoblast' | 'turisticka-oblast';
  /**
   * U podoblasti její pohoří (např. Východní Krkonoše → Krkonoše).
   */
  nadrazena?: (number | null) | Oblasti;
  zeme?: ('cz' | 'sk' | 'pl' | 'at' | 'de' | 'ch' | 'it' | 'si' | 'fr') | null;
  /**
   * Tvary do vět na webu. Bez nich se věty poskládají opisem v 1. pádu — nikdy se neskloňuje automaticky.
   */
  sklonovani?: {
    druhy?: string | null;
    sesty?: string | null;
  };
  popis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hero stránky pohoří (F1): 2–3 věty o charakteru oblasti. Superlativy jen s dokladem (zdroj do bloku ověření níže) — co není doloženo, do textu nepatří.
   */
  charakteristika?: string | null;
  /**
   * Zdroje tvrzení v kurátorské charakteristice.
   */
  overeniCharakteristika?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Stat-tile stránky pohoří (F1). Bez zdroje se dlaždice nevykresluje — nedomýšlet.
   */
  nejvyssiHora?: {
    nazev?: string | null;
    vyska?: number | null;
    source?: string | null;
  };
  /**
   * Sekce „Top cíle" stránky pohoří (F1): 1 poctivá věta na cíl + volitelná vazba na nejbližší chatu slugem. Kurátorský výběr, žádná hodnocení ani ceny.
   */
  topCile?:
    | {
        nazev: string;
        veta?: string | null;
        /**
         * Slug profilu chaty pro odkaz „Nejblíž: …" — jen když je vazba doložená.
         */
        nejblizChataSlug?: string | null;
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Krajinný snímek do hlavičky stránky pohoří. NENÍ to fotka objektu — u fotek chat musí být doložené, která budova to je (kolekce Fotky), kdežto tady stačí doložená lokalita. Soubory leží v public/foto/pohori/.
   */
  heroFoto?: {
    soubor?: string | null;
    nahled?: string | null;
    alt?: string | null;
    autor?: string | null;
    autorUrl?: string | null;
    licence?:
      | ('unsplash' | 'mediabanka-czt' | 'pexels' | 'cc-by' | 'cc-by-sa' | 'cc0' | 'pd' | 'se-svolenim' | 'vlastni')
      | null;
    zdrojUrl?: string | null;
    /**
     * Píše se jen to, co dokládá popis u zdroje. Když autor budovu nejmenuje, nejmenujeme ji ani my.
     */
    popisMista?: string | null;
    prevzatoDne?: string | null;
    /**
     * Ručně psaná popiska přes snímek (návrh F1: „Luční bouda, 1 410 m" se šipkou). Vyplň JEN tehdy, když je předmět popisky doložený — u fotky, kde autor budovu nejmenuje, by šipka ukazovala na dohad. Prázdné pole znamená, že se anotace nekreslí.
     */
    anotace?: {
      text?: string | null;
      x?: number | null;
      y?: number | null;
      /**
       * Jen když je jasné, na co ukazuje.
       */
      sipka?: boolean | null;
    };
  };
  /**
   * Kdo a čím doložil, co snímek zachycuje. `verified: true` jen tehdy, když to potvrdil člověk redakce vlastní znalostí místa — popis autora u snímku je zdroj, ne ověření (konvence B).
   */
  overeniHeroFoto?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Snímky, které nesou jednotlivé sekce (handoff F1): foto pás u top cílů a vlepený snímek u paměti hor. Titulní fotka má vlastní pole `heroFoto`. Platí totéž pravidlo: popis říká jen to, co je doložené — když nevíme, co přesně je na snímku, zůstane u fotky jen atribuce.
   */
  fotky?:
    | {
        role: 'pas-cile' | 'pamet';
        soubor?: string | null;
        nahled?: string | null;
        alt?: string | null;
        autor?: string | null;
        autorUrl?: string | null;
        licence?:
          | ('unsplash' | 'mediabanka-czt' | 'pexels' | 'cc-by' | 'cc-by-sa' | 'cc0' | 'pd' | 'se-svolenim' | 'vlastni')
          | null;
        zdrojUrl?: string | null;
        /**
         * Prázdné pole = u fotky se ukáže jen atribuce. To je v pořádku.
         */
        popis?: string | null;
        /**
         * Název ze seznamu `topCile`. Vyplň jen tehdy, když je doložené, že snímek zachycuje právě tenhle cíl — karta s cílem se pak položí do fotky. Prázdné = pás zůstane jen fotkou s popiskou.
         */
        cilNazev?: string | null;
        /**
         * Klikací body s popiskem. Vyplň jen to, co je na snímku doložené — bod ukazující na dohad je horší než snímek bez bodů.
         */
        hotspoty?:
          | {
              text: string;
              x?: number | null;
              y?: number | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Kdo a čím doložil, co je na fotce (konvence B).
         */
        overeni?: {
          source?: string | null;
          verified?: boolean | null;
          checked?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Volitelné ohraničení pro výřez mapy oblasti (WGS84).
   */
  bbox?: {
    jihLat?: number | null;
    zapadLng?: number | null;
    severLat?: number | null;
    vychodLng?: number | null;
  };
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeni?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Každá fotka má autora a licenci; převzaté i zdrojové URL. Fotky z Google Maps a Mapy.com se nepoužívají nikdy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fotky".
 */
export interface Fotky {
  id: number;
  alt: string;
  typ?: ('soucasna' | 'dobova' | 'otisk-razitka' | 'ilustracni' | 'komunitni-podani') | null;
  /**
   * Fotka se pak sama nabídne v profilu chaty.
   */
  chata?: (number | null) | Chaty;
  /**
   * Fotka se pak ukáže na kartě i mini-stránce střediska — místo snímku z Commons.
   */
  stredisko?: (number | null) | Strediska;
  /**
   * Lanovka nemá vlastní kolekci (vzniká z OSM) — váže se oblastí a slugem z přehledu lanovek.
   */
  lanovkaOblast?: string | null;
  lanovkaSlug?: string | null;
  datovani?: string | null;
  autor: string;
  licence: 'vlastni' | 'se-svolenim' | 'cc-by' | 'cc-by-sa' | 'cc0' | 'pd' | 'mediabanka-czt' | 'jina';
  licencePoznamka?: string | null;
  /**
   * U převzatých fotek povinné (Wikimedia Commons apod.).
   */
  zdrojUrl?: string | null;
  /**
   * Proč smí snímek na web. „Nevyjasněno" je poctivý stav pro rozpracované — takový snímek se nepoužije.
   */
  pravniStatus?: ('volne-autor' | 'volne-anonym' | 'cc' | 'se-svolenim' | 'nevyjasneno') | null;
  instituce?: string | null;
  signatura?: string | null;
  rokVydani?: string | null;
  puvodOriginalu?: string | null;
  /**
   * Čím je status doložen: „autor A. Novák zemřel 1943", „anonym, vydáno 1928 dle rubu", „svolení sbírky X z 12. 6. 2026". Bez toho se za rok nedá přezkoumat, proč snímek na webu je.
   */
  pravniPoznamka?: string | null;
  prevzatoDne?: string | null;
  /**
   * Ověření licence a autorství (kdo a kdy je zkontroloval).
   */
  overeni?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Kdo fotku poslal a jeho licenční souhlas. Schválení = po kontrole přepnout Typ (tím se fotka pustí do výběrů šablon) — bez souhlasu to hook nedovolí.
   */
  podani?: {
    hostJmeno?: string | null;
    /**
     * Neveřejné — jen pro redakci (kontakt k podání).
     */
    hostEmail?: string | null;
    /**
     * Odesilatel potvrdil, že snímek sám pořídil / má k němu práva a souhlasí se zveřejněním s uvedením jména (licence „se svolením").
     */
    licencniSouhlas?: boolean | null;
    souhlasZneni?: string | null;
    souhlasDatum?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    nahled?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    karta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    velka?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Východiště do hor (Pec, Špindl, Harrachov…). Počty chat a rozpětí přístupů se počítají z tras — neukládají se.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strediska".
 */
export interface Strediska {
  id: number;
  nazev: string;
  /**
   * Část adresy stránky. Nevyplněný se vytvoří z názvu.
   */
  slug: string;
  zeme?: ('cz' | 'sk' | 'pl' | 'at' | 'de' | 'ch' | 'it' | 'si' | 'fr') | null;
  oblast?: (number | null) | Oblasti;
  /**
   * Hero mini-stránky: 2 věty, jen doložitelné údaje — žádné ceníky ani hodnocení.
   */
  perex?: string | null;
  lat?: number | null;
  lng?: number | null;
  /**
   * Stat-tile „výška obce" — zdroj ČÚZK do bloku ověření.
   */
  vyskaObce?: number | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniLokace?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Názvy výchozích bodů z katalogu DATA-06 (data/oblasti/<oblast>/vychozi-body-kandidati.json), které patří k tomuto středisku. Přes ně se při buildu počítá „chat dostupných odtud" a rozpětí přístupů — vazba dat, žádná ručně psaná čísla.
   */
  vychoziBody?:
    | {
        nazev: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Jen doložený fakt (např. „kabinová lanovka na Sněžku") — bez jízdních řádů.
   */
  lanovka?: string | null;
  /**
   * Fakta o dopravním napojení (vlak/bus/auto) — žádné jízdní řády.
   */
  doprava?: {
    vlak?: string | null;
    bus?: string | null;
    auto?: string | null;
  };
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeniDoprava?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  /**
   * Jen pro redakci, nikdy se nezobrazují na webu.
   */
  interniPoznamky?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Katalog turistických razítek — archiv variant v čase. Záznam může existovat i bez otisku (víme o razítku, sháníme sken). Komunitní podání čeká jako koncept, než ho redakce publikuje.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "razitka".
 */
export interface Razitka {
  id: number;
  nazev: string;
  chata: number | Chaty;
  /**
   * Může chybět — chybějící otisky jsou výzva pro komunitu.
   */
  otisk?: (number | null) | Fotky;
  stav?: ('k-dispozici' | 'nedostupne' | 'historicke') | null;
  platnostOd?: string | null;
  platnostDo?: string | null;
  kdeSeRazitkuje?: string | null;
  /**
   * Veřejný kredit — redakce, nebo jméno/přezdívka sběratele. U komunitních podání se předvyplní z podání níže.
   */
  dolozil?: string | null;
  /**
   * Kdy někdo naposledy potvrdil, že se razítko na chatě opravdu razítkuje.
   */
  potvrzeno?: string | null;
  poznamka?: string | null;
  /**
   * Komunitní podání čeká jako koncept, dokud ho redakce nepublikuje. Publikovat ho nelze bez licenčního souhlasu níže. Převzaté (partnerský web) nelze publikovat bez odkazu na zdroj.
   */
  zpusobZiskani?: ('redakce' | 'komunitni-podani' | 'prevzato-se-svolenim') | null;
  /**
   * Kdo otisk nahrál a jeho licenční souhlas. Sběratel může podat s účtem i jako host (bez účtu).
   */
  podani?: {
    /**
     * Vyplněno, když otisk nahrál přihlášený sběratel. U hostů zůstane prázdné.
     */
    ucet?: (number | null) | User;
    hostJmeno?: string | null;
    /**
     * Neveřejné — jen pro redakci (kontakt k podání).
     */
    hostEmail?: string | null;
    /**
     * Nahrávající potvrdil, že otisk sám naskenoval / vlastní a uděluje souhlas se zveřejněním s uvedením kreditu (licence „se svolením"). Bez zaškrtnutí nelze publikovat.
     */
    licencniSouhlas?: boolean | null;
    /**
     * Text souhlasu tak, jak byl při nahrání odsouhlasen (pro doložení).
     */
    souhlasZneni?: string | null;
    souhlasDatum?: string | null;
  };
  /**
   * Otisk převzatý z partnerského webu s jeho svolením. Zdroj (odkaz) se povinně zobrazuje u razítka na webu — bez `zdrojUrl` nelze publikovat.
   */
  prevzeti?: {
    zdroj?: string | null;
    zdrojUrl?: string | null;
    svolil?: string | null;
  };
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeni?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Redakční obsah: historie, rozhovory, žebříčky, příběhy zaniklých chat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clanky".
 */
export interface Clanky {
  id: number;
  nazev: string;
  /**
   * Část adresy stránky. Nevyplněný se vytvoří z názvu.
   */
  slug: string;
  publikovano?: string | null;
  perex?: string | null;
  uvodniFotka?: (number | null) | Fotky;
  obsah?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  chaty?: (number | Chaty)[] | null;
  oblasti?: (number | Oblasti)[] | null;
  /**
   * Zdroje faktů v článku (historická literatura, rozhovory…).
   */
  overeni?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Redakční výlety a přechody. Každá chata má mít aspoň jeden propojený výlet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vylety".
 */
export interface Vylety {
  id: number;
  nazev: string;
  /**
   * Část adresy stránky. Nevyplněný se vytvoří z názvu.
   */
  slug: string;
  typ?: ('okruh' | 'prechod' | 'tam-a-zpet') | null;
  oblast?: (number | null) | Oblasti;
  delkaKm?: number | null;
  prevyseni?: number | null;
  casMin?: number | null;
  obtiznost?: ('snadna' | 'stredni' | 'narocna') | null;
  sezonnost?: string | null;
  znaceni?: ('cervena' | 'modra' | 'zelena' | 'zluta' | 'cerna' | 'jine')[] | null;
  gpx?: (number | null) | Media;
  perex?: string | null;
  zastavky?:
    | {
        typ?: ('chata' | 'vrchol' | 'misto') | null;
        chata?: (number | null) | Chaty;
        /**
         * U vrcholů a jiných míst; u chat se bere název chaty.
         */
        nazev?: string | null;
        poznamka?: string | null;
        id?: string | null;
      }[]
    | null;
  doprava?: {
    naStart?: string | null;
    zCile?: string | null;
  };
  etapy?:
    | {
        nadpis: string;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Odkud údaje v této skupině pocházejí a kdy byly naposledy ověřeny. Nikdy nedomýšlet fakta.
   */
  overeni?: {
    source?: string | null;
    verified?: boolean | null;
    checked?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * GPX stopy a jiné přílohy. Fotky patří do kolekce Fotky (kvůli licencím).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'chaty';
        value: number | Chaty;
      } | null)
    | ({
        relationTo: 'oblasti';
        value: number | Oblasti;
      } | null)
    | ({
        relationTo: 'strediska';
        value: number | Strediska;
      } | null)
    | ({
        relationTo: 'vylety';
        value: number | Vylety;
      } | null)
    | ({
        relationTo: 'razitka';
        value: number | Razitka;
      } | null)
    | ({
        relationTo: 'clanky';
        value: number | Clanky;
      } | null)
    | ({
        relationTo: 'fotky';
        value: number | Fotky;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chaty_select".
 */
export interface ChatySelect<T extends boolean = true> {
  nazev?: T;
  slug?: T;
  zeme?: T;
  typ?: T;
  stav?: T;
  aliasy?:
    | T
    | {
        nazev?: T;
        poznamka?: T;
        id?: T;
      };
  lat?: T;
  lng?: T;
  vyska?: T;
  oblast?: T;
  obec?: T;
  overeniLokace?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  nocleh?: T;
  pokoje?:
    | T
    | {
        typ?: T;
        luzek?: T;
        id?: T;
      };
  kapacita?: T;
  cenyOrientacne?: T;
  rezervaceUrl?: T;
  overeniNocleh?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  kuchyne?: T;
  typObcerstveni?: T;
  specialita?: T;
  overeniObcerstveni?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  voda?: T;
  wc?: T;
  sprchy?: T;
  platbaKartou?: T;
  wifi?: T;
  psi?: T;
  nabijeni?: T;
  lyzarna?: T;
  overeniSluzby?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  sezona?: T;
  otviraciDoba?: T;
  zimniProvoz?: T;
  kontakty?:
    | T
    | {
        telefon?: T;
        email?: T;
        web?: T;
        facebook?: T;
        instagram?: T;
      };
  overeniProvoz?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  trasy?:
    | T
    | {
        vychoziBod?: T;
        casMin?: T;
        prevyseni?: T;
        znaceni?: T;
        obtiznost?: T;
        poznamka?: T;
        delkaKm?: T;
        vyskovyProfil?: T;
        id?: T;
      };
  autem?: T;
  lanovka?: T;
  verejnaDoprava?:
    | T
    | {
        zastavka?: T;
        idosUrl?: T;
      };
  overeniPristup?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  rokVzniku?: T;
  milniky?:
    | T
    | {
        rok?: T;
        udalost?: T;
        id?: T;
      };
  historieText?: T;
  overeniHistorie?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  perex?: T;
  text?: T;
  zajimavosti?:
    | T
    | {
        text?: T;
        kategorie?: T;
        zdroj?: T;
        id?: T;
      };
  fotky?: T;
  webkamera?: T;
  sousedniChaty?:
    | T
    | {
        chata?: T;
        casPrechodMin?: T;
        id?: T;
      };
  razitka?: T;
  clanky?: T;
  zdroje?:
    | T
    | {
        popis?: T;
        url?: T;
        id?: T;
      };
  interniPoznamky?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oblasti_select".
 */
export interface OblastiSelect<T extends boolean = true> {
  nazev?: T;
  slug?: T;
  typ?: T;
  nadrazena?: T;
  zeme?: T;
  sklonovani?:
    | T
    | {
        druhy?: T;
        sesty?: T;
      };
  popis?: T;
  charakteristika?: T;
  overeniCharakteristika?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  nejvyssiHora?:
    | T
    | {
        nazev?: T;
        vyska?: T;
        source?: T;
      };
  topCile?:
    | T
    | {
        nazev?: T;
        veta?: T;
        nejblizChataSlug?: T;
        source?: T;
        id?: T;
      };
  heroFoto?:
    | T
    | {
        soubor?: T;
        nahled?: T;
        alt?: T;
        autor?: T;
        autorUrl?: T;
        licence?: T;
        zdrojUrl?: T;
        popisMista?: T;
        prevzatoDne?: T;
        anotace?:
          | T
          | {
              text?: T;
              x?: T;
              y?: T;
              sipka?: T;
            };
      };
  overeniHeroFoto?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  fotky?:
    | T
    | {
        role?: T;
        soubor?: T;
        nahled?: T;
        alt?: T;
        autor?: T;
        autorUrl?: T;
        licence?: T;
        zdrojUrl?: T;
        popis?: T;
        cilNazev?: T;
        hotspoty?:
          | T
          | {
              text?: T;
              x?: T;
              y?: T;
              id?: T;
            };
        overeni?:
          | T
          | {
              source?: T;
              verified?: T;
              checked?: T;
            };
        id?: T;
      };
  bbox?:
    | T
    | {
        jihLat?: T;
        zapadLng?: T;
        severLat?: T;
        vychodLng?: T;
      };
  overeni?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strediska_select".
 */
export interface StrediskaSelect<T extends boolean = true> {
  nazev?: T;
  slug?: T;
  zeme?: T;
  oblast?: T;
  perex?: T;
  lat?: T;
  lng?: T;
  vyskaObce?: T;
  overeniLokace?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  vychoziBody?:
    | T
    | {
        nazev?: T;
        id?: T;
      };
  lanovka?: T;
  doprava?:
    | T
    | {
        vlak?: T;
        bus?: T;
        auto?: T;
      };
  overeniDoprava?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  interniPoznamky?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vylety_select".
 */
export interface VyletySelect<T extends boolean = true> {
  nazev?: T;
  slug?: T;
  typ?: T;
  oblast?: T;
  delkaKm?: T;
  prevyseni?: T;
  casMin?: T;
  obtiznost?: T;
  sezonnost?: T;
  znaceni?: T;
  gpx?: T;
  perex?: T;
  zastavky?:
    | T
    | {
        typ?: T;
        chata?: T;
        nazev?: T;
        poznamka?: T;
        id?: T;
      };
  doprava?:
    | T
    | {
        naStart?: T;
        zCile?: T;
      };
  etapy?:
    | T
    | {
        nadpis?: T;
        text?: T;
        id?: T;
      };
  overeni?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "razitka_select".
 */
export interface RazitkaSelect<T extends boolean = true> {
  nazev?: T;
  chata?: T;
  otisk?: T;
  stav?: T;
  platnostOd?: T;
  platnostDo?: T;
  kdeSeRazitkuje?: T;
  dolozil?: T;
  potvrzeno?: T;
  poznamka?: T;
  zpusobZiskani?: T;
  podani?:
    | T
    | {
        ucet?: T;
        hostJmeno?: T;
        hostEmail?: T;
        licencniSouhlas?: T;
        souhlasZneni?: T;
        souhlasDatum?: T;
      };
  prevzeti?:
    | T
    | {
        zdroj?: T;
        zdrojUrl?: T;
        svolil?: T;
      };
  overeni?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clanky_select".
 */
export interface ClankySelect<T extends boolean = true> {
  nazev?: T;
  slug?: T;
  publikovano?: T;
  perex?: T;
  uvodniFotka?: T;
  obsah?: T;
  chaty?: T;
  oblasti?: T;
  overeni?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fotky_select".
 */
export interface FotkySelect<T extends boolean = true> {
  alt?: T;
  typ?: T;
  chata?: T;
  stredisko?: T;
  lanovkaOblast?: T;
  lanovkaSlug?: T;
  datovani?: T;
  autor?: T;
  licence?: T;
  licencePoznamka?: T;
  zdrojUrl?: T;
  pravniStatus?: T;
  instituce?: T;
  signatura?: T;
  rokVydani?: T;
  puvodOriginalu?: T;
  pravniPoznamka?: T;
  prevzatoDne?: T;
  overeni?:
    | T
    | {
        source?: T;
        verified?: T;
        checked?: T;
      };
  podani?:
    | T
    | {
        hostJmeno?: T;
        hostEmail?: T;
        licencniSouhlas?: T;
        souhlasZneni?: T;
        souhlasDatum?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        nahled?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        karta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        velka?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}